# Generated by Django 4.2 on 2023-04-27 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Užsakymas',
                'verbose_name_plural': 'Užsakymai',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Įveskite paslaugos pavadinimą', max_length=200, verbose_name='Pavadinimas')),
                ('price', models.CharField(help_text='Įveskite paslaugos kainą', max_length=5, verbose_name='Kaina')),
            ],
            options={
                'verbose_name': 'Paslauga',
                'verbose_name_plural': 'Paslaugos',
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(max_length=50, verbose_name='Gamintojas')),
                ('modelis', models.CharField(max_length=50, verbose_name='Modelis')),
            ],
            options={
                'verbose_name': 'Automobilio modelis',
                'verbose_name_plural': 'Automobilių modeliai',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=7, verbose_name='Valst_Numeris')),
                ('vin_code', models.CharField(max_length=15, verbose_name='VIN')),
                ('client', models.CharField(max_length=25, verbose_name='Klientas')),
                ('vehicle_model', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.vehiclemodel')),
            ],
            options={
                'verbose_name': 'Automobilis',
                'verbose_name_plural': 'Automobiliai',
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=2, verbose_name='Kiekis')),
                ('order', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.order', verbose_name='Užsakymas')),
                ('service', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.service', verbose_name='Paslauga')),
            ],
            options={
                'verbose_name': 'Užsakymo eilutė',
                'verbose_name_plural': 'Užsakymo eilutės',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.vehicle', verbose_name='Automobilis'),
        ),
    ]
